"""BV.7 — trainer-cards byte-identity verifier surface.

Walks :data:`recon_gen.common.l2.plant_registry.PLANT_REGISTRY` and
:func:`recon_gen.common.html._studio_training_v2.resolve_section` and
emits one Markdown ``##`` section per kind containing the canonical
``short_statement`` + ``what_to_do`` text that the Trainer's
``/training/`` v3 panel renders on each card (per BU.0 Lock 8).

This surface is a BYTE-IDENTITY verifier — the same dispatch already
drives the live Trainer cards. The generated artifact is committed at
``tests/data/_handbook_artifacts/trainer_cards.md`` so a downstream
edit to either the registry (kind added / renamed) or the typed-section
catalogues (`InvariantSection` / `L2FTExceptionSection` /
`L2TriageGapSection` prose touched) fails CI loudly until the
reference is refreshed.

Output shape: a leading H1 + a one-paragraph "this is generated"
preamble + one ``## {kind}`` per registry entry, each followed by:

- a ``**Short statement:**`` paragraph (``section.short_statement``);
- a ``**What to do:**`` paragraph (``section.what_to_do``).

The CLI surface lives in :mod:`recon_gen.cli.docs` as
``recon-gen docs export --surface=trainer-cards``.
"""

from __future__ import annotations

from recon_gen.common.html._studio_training_v2 import resolve_section
from recon_gen.common.l2.plant_registry import (
    PLANT_REGISTRY,
    PlantKindEntry,
)


def _render_entry(entry: PlantKindEntry) -> str:
    """Render one ``## {kind}`` section for ``entry``.

    The header is the canonical machine ``kind`` (matches the registry
    slug + the §0.5 coverage matrix's ``Kind`` column) so a reader
    grepping a kind name lands on the right card without decoding the
    section title's free-text rendering.
    """
    section = resolve_section(entry)
    short = section.short_statement.strip()
    what_to_do = section.what_to_do.strip()
    return (
        f"## {entry.kind}\n"
        "\n"
        f"**Short statement:** {short}\n"
        "\n"
        f"**What to do:** {what_to_do}\n"
    )


def render_trainer_cards() -> str:
    """Walk PLANT_REGISTRY + emit one ``##`` block per kind as Markdown.

    Output shape: H1 + provenance preamble + one ``## {kind}`` block
    per registry entry, joined by a blank line. Pinned to the
    committed reference artifact under
    ``tests/data/_handbook_artifacts/trainer_cards.md``.
    """
    blocks = [_render_entry(entry) for entry in PLANT_REGISTRY]
    preamble = (
        "# Trainer cards (resolve_section output)\n"
        "\n"
        "Generated by `recon-gen docs export --surface=trainer-cards` — "
        "do not hand-edit. Source of truth is "
        "`src/recon_gen/common/l2/plant_registry.py::PLANT_REGISTRY` "
        "walked through "
        "`recon_gen.common.html._studio_training_v2.resolve_section` "
        "(BU.0 Lock 8). One `##` block per kind carries the canonical "
        "`short_statement` + `what_to_do` strings the Trainer's "
        "`/training/` v3 cards render — byte-identity verifier per "
        "BU.0 Lock 9.\n"
        "\n"
        f"Row count: **{len(blocks)}** kinds.\n"
        "\n"
    )
    return preamble + "\n".join(blocks)
