"""BV.7 Surface 2 — violations handbook (single-bundle Markdown) generator.

Walks :data:`recon_gen.common.l2.plant_registry.PLANT_REGISTRY` through
:func:`recon_gen.common.html._studio_training_v2.resolve_section` and
emits a single Markdown document with one ``##`` section per kind,
each carrying a slugified anchor ID so the BTa.1 / BX.12 side-panel
system can deep-link via ``/training/violations.md#<slug>`` (or the
equivalent docs-site path).

Output shape — pinned to the committed reference artifact under
``tests/data/_handbook_artifacts/violations.md`` (BU.0 Lock 9
byte-identity):

- a leading H1 + provenance preamble + row-count line;
- a "Contents" table-of-contents linking every kind by anchor slug;
- one ``## {section.title} {#kind-slug}`` block per registry entry,
  each followed by:

  - a ``**Kind:**`` line (canonical machine ``kind``);
  - a ``### Short statement`` paragraph (``section.short_statement``);
  - a ``### What to do`` paragraph (``section.what_to_do``);
  - a ``**Section reference:**`` cross-link to the typed source class
    (the same ``ClassName["section_kind"]`` cell the §0.5 coverage
    matrix renders, so a reader can grep one artifact's anchor and
    land on the other's row).

The slug is ``entry.kind`` lowercased with underscores → hyphens —
stable across renders, deep-linkable, and grep-friendly. Per BV.7
operator lock (2026-06-09) the slug derivation lives here, not on the
registry entry, so a kind rename remains a one-edit change.

The CLI surface lives in :mod:`recon_gen.cli.docs` as
``recon-gen docs export --surface=violations``.
"""

from __future__ import annotations

from recon_gen.common.handbook.coverage_matrix import _typed_source_for
from recon_gen.common.html._studio_training_v2 import resolve_section
from recon_gen.common.l2.plant_registry import (
    PLANT_REGISTRY,
    PlantKindEntry,
)


def _slug_for(entry: PlantKindEntry) -> str:
    """Derive the deep-link anchor slug from ``entry.kind``.

    Lowercase + underscores-to-hyphens — kebab-case for URL safety,
    stable across renders, grep-friendly. Per BV.7 operator lock the
    slug is a property of the rendering layer (not the registry
    entry), so a kind rename touches one site.
    """
    return entry.kind.lower().replace("_", "-")


def _render_toc(entries: list[PlantKindEntry]) -> str:
    """Render the table-of-contents block.

    One bullet per kind: ``- [{title}](#{slug}) — `{kind}`​``. Title
    comes from the typed section so the TOC reads like the page; the
    inline ``kind`` code-span lets the reader confirm slug derivation
    at a glance.
    """
    lines = ["## Contents", ""]
    for entry in entries:
        section = resolve_section(entry)
        slug = _slug_for(entry)
        lines.append(
            f"- [{section.title}](#{slug}) — `{entry.kind}`"
        )
    lines.append("")
    return "\n".join(lines)


def _render_entry(entry: PlantKindEntry) -> str:
    """Render one ``## {title} {#slug}`` block for ``entry``.

    The ``{#slug}`` syntax is a kramdown / python-markdown
    ``attr_list``-compatible anchor — every modern Markdown renderer
    in the toolchain (mkdocs-material, GitHub, the BTa.1 docs panel)
    honors it so the deep-link resolves verbatim.
    """
    section = resolve_section(entry)
    slug = _slug_for(entry)
    short = section.short_statement.strip()
    what_to_do = section.what_to_do.strip()
    typed_ref = _typed_source_for(entry)
    return (
        f"## {section.title} {{#{slug}}}\n"
        "\n"
        f"**Kind:** `{entry.kind}`\n"
        "\n"
        "### Short statement\n"
        "\n"
        f"{short}\n"
        "\n"
        "### What to do\n"
        "\n"
        f"{what_to_do}\n"
        "\n"
        f"**Section reference:** {typed_ref}\n"
    )


def render_violations_handbook() -> str:
    """Walk PLANT_REGISTRY + emit the single-bundle violations
    handbook as Markdown.

    Output shape: H1 + provenance preamble + row-count + TOC + one
    ``## {title} {#slug}`` block per registry entry, joined by a
    blank line. Pinned to the committed reference artifact under
    ``tests/data/_handbook_artifacts/violations.md``.
    """
    entries = list(PLANT_REGISTRY)
    toc = _render_toc(entries)
    blocks = [_render_entry(entry) for entry in entries]
    preamble = (
        "# Violations handbook\n"
        "\n"
        "Generated by `recon-gen docs export --surface=violations` — "
        "do not hand-edit. Source of truth is "
        "`src/recon_gen/common/l2/plant_registry.py::PLANT_REGISTRY` "
        "walked through "
        "`recon_gen.common.html._studio_training_v2.resolve_section` "
        "(BU.0 Lock 8). One `##` block per kind carries the canonical "
        "`short_statement` + `what_to_do` strings the Trainer's "
        "`/training/` v3 cards render — deep-linkable from the BTa.1 / "
        "BX.12 side-panel system via slug anchors (`#<kind-as-kebab>`). "
        "Byte-identity verifier per BU.0 Lock 9.\n"
        "\n"
        f"Row count: **{len(entries)}** kinds.\n"
        "\n"
    )
    return preamble + toc + "\n" + "\n".join(blocks)
