"""Generate the auto-doc markdown section from PARITY_BREAKS.

Per CN.0 Lock CN-5 (the registry IS the source) + CN.6 mkdocs gate
(handbook ↔ registry consistency). This module emits the registry as
a stable-ordered markdown section that gets folded into
:file:`docs/reference/quicksight-quirks.md` or rendered as its own
page under :file:`docs/reference/qs-parity-breaks.md`.

Stable-ordered = sorted by ``(severity, discovered, name)`` so the
emitted markdown's diff is meaningful when new entries land — only
the new entries' blocks appear in the diff, not a reshuffle of the
full file.

Entry points:

- :func:`render_markdown` — full markdown for the registry's auto-doc.
- :func:`render_handbook_section` — short per-sheet "QS parity notes"
  snippet for a handbook page (filtered to entries the page should
  surface).
"""

from __future__ import annotations

from collections.abc import Iterable

from .breaks import PARITY_BREAKS, ParitySeverity, QSParityBreak


_SEVERITY_RANK: dict[ParitySeverity, int] = {
    ParitySeverity.WORKAROUND: 0,        # the things we ROUTE AROUND first
    ParitySeverity.HARD_DIVERGENCE: 1,   # the things QS CANNOT host next
    ParitySeverity.ENHANCEMENT: 2,       # the things App2 just does BETTER
}

_SEVERITY_HEADING: dict[ParitySeverity, str] = {
    ParitySeverity.WORKAROUND:
        "Workarounds (App2 routes around a QS bug or limit)",
    ParitySeverity.HARD_DIVERGENCE:
        "Hard divergences (QS literally cannot host this surface)",
    ParitySeverity.ENHANCEMENT:
        "Enhancements (App2 richer; QS still works)",
}


def _sort_key(e: QSParityBreak) -> tuple[int, str, str]:
    return (_SEVERITY_RANK[e.severity], e.discovered, e.name)


def _format_entry(e: QSParityBreak) -> str:
    parts = [
        f"### `{e.name}`",
        "",
        f"**Discovered:** {e.discovered}",
        "",
        f"**Surface (App2):** {e.surface}",
        "",
        f"**QS limitation:** {e.qs_limitation}",
    ]
    if e.references:
        parts.append("")
        parts.append("**References:**")
        for ref in e.references:
            parts.append(f"- `{ref}`")
    return "\n".join(parts)


def render_markdown(
    entries: Iterable[QSParityBreak] = PARITY_BREAKS,
) -> str:
    """Return the full auto-doc markdown for the registry.

    Group order: WORKAROUND → HARD_DIVERGENCE → ENHANCEMENT (so the
    operator-affecting items come first); within each group, sorted by
    ``(discovered, name)`` so additions append to their group block.
    """
    sorted_entries = sorted(entries, key=_sort_key)
    lines = [
        "# QuickSight Parity Breaks",
        "",
        "Auto-generated from `src/recon_gen/common/parity/breaks.py`.",
        "Do not edit this file by hand; the registry is the source.",
        "",
        "Each entry below records a deliberate divergence between App2 "
        "(the self-hosted HTMX renderer) and QuickSight (the AWS embed). "
        "Adding a new break: append a `QSParityBreak` entry to "
        "`PARITY_BREAKS` and regenerate this file.",
        "",
    ]
    current_severity: ParitySeverity | None = None
    for e in sorted_entries:
        if e.severity != current_severity:
            current_severity = e.severity
            lines.append(f"## {_SEVERITY_HEADING[e.severity]}")
            lines.append("")
        lines.append(_format_entry(e))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_handbook_section(
    names: Iterable[str],
    entries: Iterable[QSParityBreak] = PARITY_BREAKS,
) -> str:
    """Return a short "QS parity notes" section for a handbook page.

    ``names`` is the subset of `PARITY_BREAK.name` strings the page
    should surface (e.g. a sheet's handbook page might cite
    ``count_distinct_quirk_bl1`` + ``dependent_dropdown_no_refresh_x223``).

    Output is a markdown bullet list with one line per cited break.
    Used by the handbook author OR by a future automated doc-gen step.
    """
    by_name = {e.name: e for e in entries}
    wanted = [n for n in names if n in by_name]
    if not wanted:
        return ""
    lines = ["## QS parity notes", ""]
    for n in wanted:
        e = by_name[n]
        lines.append(
            f"- **`{n}`** — {e.surface} "
            f"QS limitation: {e.qs_limitation}"
        )
    return "\n".join(lines) + "\n"
